
services:

    model.recipe:
        class: AppBundle\Model\RecipeModel
        arguments:
            - '@doctrine.orm.entity_manager'

    model.ingredient:
        class: AppBundle\Model\IngredientModel
        arguments:
            - '@doctrine.orm.entity_manager'
